"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var dashboard_controller_1 = require("../controllers/dashboard.controller");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var rbac_middleware_1 = require("../middlewares/rbac.middleware");
var router = (0, express_1.Router)();
router.get('/kpis', auth_middleware_1.authenticate, (0, rbac_middleware_1.requireRole)(rbac_middleware_1.Role.ADMINISTRADOR, rbac_middleware_1.Role.GERENTE_VENTAS), dashboard_controller_1.dashboardController.obtenerKPIs);
router.get('/ventas-diarias', auth_middleware_1.authenticate, (0, rbac_middleware_1.requireRole)(rbac_middleware_1.Role.ADMINISTRADOR, rbac_middleware_1.Role.GERENTE_VENTAS), dashboard_controller_1.dashboardController.ventasDiarias);
router.get('/ventas-categoria', auth_middleware_1.authenticate, (0, rbac_middleware_1.requireRole)(rbac_middleware_1.Role.ADMINISTRADOR, rbac_middleware_1.Role.GERENTE_VENTAS), dashboard_controller_1.dashboardController.ventasPorCategoria);
router.get('/top-productos', auth_middleware_1.authenticate, (0, rbac_middleware_1.requireRole)(rbac_middleware_1.Role.ADMINISTRADOR, rbac_middleware_1.Role.GERENTE_VENTAS), dashboard_controller_1.dashboardController.topProductos);
exports.default = router;
